# Generated by Django 2.2.11 on 2020-09-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelUserGroupMapping',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('panel_name', models.CharField(max_length=100, verbose_name='Panel Name')),
                ('category', djongo.models.fields.ArrayField(model_container=user_profile.models.Category)),
                ('supervisor_pool', djongo.models.fields.ArrayField(model_container=user_profile.models.SupervisorPool)),
                ('reviewer_pool', djongo.models.fields.ArrayField(model_container=user_profile.models.ReviewerPool)),
            ],
            options={
                'verbose_name': 'Panel User Group Mapping',
                'verbose_name_plural': 'Panel User Group Mapping',
                'db_table': 'ccrh_panel_user_group_mapping',
            },
        ),
        migrations.CreateModel(
            name='PractDetails',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('pract_regis_body', models.CharField(max_length=10, verbose_name='Registration Body')),
                ('pract_reg_no', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('document_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Name')),
                ('document_path', models.FileField(blank=True, null=True, upload_to=user_profile.models.registartion_document_path_name, verbose_name='Registration Document')),
                ('clinical_setting', djongo.models.fields.ArrayField(model_container=user_profile.models.CsPractDetails, model_form_class=user_profile.models.CsPractDetailsForm)),
                ('tnc', models.BooleanField(default=False, verbose_name='Terms & Conditions')),
                ('pract_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.State', verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Practitioner Details',
                'verbose_name_plural': 'Practitioner Details',
                'db_table': 'ccrh_pract_details',
            },
        ),
        migrations.CreateModel(
            name='AdditionalProfile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='Profile_image/', verbose_name='Profile Photo')),
                ('mobile_no', models.BigIntegerField(verbose_name='Mobile Number')),
                ('addt_mobile_no', models.BigIntegerField(blank=True, null=True, verbose_name='Additional Mobile Number')),
                ('address', djongo.models.fields.EmbeddedField(model_container=user_profile.models.AddressAdditionalProfile, model_form_class=user_profile.models.AddressAdditionalProfileForm, null=True)),
                ('profile_info', djongo.models.fields.EmbeddedField(model_container=user_profile.models.ProfileInfoAdditionalProfile, model_form_class=user_profile.models.ProfileInfoAdditionalProfileForm, null=True)),
                ('profile_status', models.CharField(blank=True, max_length=100, null=True, verbose_name=' Profile Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Additional Profile',
                'verbose_name_plural': 'Additional Profile',
                'db_table': 'ccrh_user_addtional_profile',
            },
        ),
    ]
