# Generated by Django 2.2.11 on 2020-09-02 13:42

import case_history.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=250, verbose_name='Case ID')),
                ('case_title', models.CharField(max_length=150, verbose_name='Case Title')),
                ('keywords', djongo.models.fields.EmbeddedField(model_container=case_history.models.Keywords, model_form_class=case_history.models.KeywordsForm, null=True)),
                ('keyword_index', models.TextField(verbose_name='Keyword Index')),
                ('case_summary', models.TextField(verbose_name='Case Summary')),
                ('case_pract_id', models.CharField(max_length=150, verbose_name='Practitioner Registrations No')),
                ('name_of_institute_unit', models.CharField(max_length=250, verbose_name='Name of Institute')),
                ('diagnosis', djongo.models.fields.EmbeddedField(model_container=case_history.models.Diagnosis, model_form_class=case_history.models.DiagnosisForm, null=True)),
                ('case_status', models.CharField(help_text='Values will be stored as Submitted, Saved, Accepted, Under Review, Not Accepted, Processed, Reviewed, Published etc', max_length=150, verbose_name='Case Status')),
                ('case_category', models.CharField(max_length=150, verbose_name='Case Category')),
                ('case_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaseReviewer', to=settings.AUTH_USER_MODEL, verbose_name='Case Reviewer')),
                ('case_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaseSupervisor', to=settings.AUTH_USER_MODEL, verbose_name='Case Supervisor')),
            ],
            options={
                'verbose_name': 'Case History',
                'verbose_name_plural': 'Case History',
                'db_table': 'ccrh_case_history',
            },
        ),
        migrations.CreateModel(
            name='CaseRepertorisation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('computerized_manual_report', models.FileField(upload_to='Repertorisation_Upload/', verbose_name='Computerized / Manual Report')),
                ('symptoms_repertorized', djongo.models.fields.ArrayField(model_container=case_history.models.SymptomsRepertorized, model_form_class=case_history.models.SymptomsRepertorizedForm, null=True)),
                ('medicines', djongo.models.fields.ArrayField(model_container=case_history.models.Medicine, model_form_class=case_history.models.MedicineForm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Repertorisation ',
                'verbose_name_plural': 'Case Repertorisation ',
                'db_table': 'ccrh_case_repertorisation',
            },
        ),
        migrations.CreateModel(
            name='CasePhysicalExaminationFindings',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('general_examination', djongo.models.fields.EmbeddedField(model_container=case_history.models.GeneralExamination, model_form_class=case_history.models.GeneralExaminationForm, null=True)),
                ('systemic_examination', djongo.models.fields.EmbeddedField(model_container=case_history.models.SystemicExamination, model_form_class=case_history.models.SystemicExaminationForm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Physical Examination Findings',
                'verbose_name_plural': 'Case Physical Examination Findings',
                'db_table': 'ccrh_case_phy_examination_finding',
            },
        ),
        migrations.CreateModel(
            name='CasePersonalHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('habits', djongo.models.fields.ArrayField(model_container=case_history.models.Habits, model_form_class=case_history.models.HabitsForm)),
                ('diets', djongo.models.fields.ArrayField(model_container=case_history.models.Diets, model_form_class=case_history.models.DietsForm)),
                ('case_patient_economy_status', models.CharField(help_text='Values will be stored as 1-Lower,2-Middle,3-Higher', max_length=25, verbose_name='Economy Status')),
                ('hobbies', models.TextField(blank=True, null=True, verbose_name='Hobbies')),
                ('evolutionary_history', djongo.models.fields.EmbeddedField(model_container=case_history.models.EvolutionaryHistory, model_form_class=case_history.models.EvolutionaryHistoryForm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Personal History',
                'verbose_name_plural': 'Case Personal History',
                'db_table': 'ccrh_case_personal_history',
            },
        ),
        migrations.CreateModel(
            name='CasePastHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('past_history', djongo.models.fields.ArrayField(model_container=case_history.models.PastHistory, model_form_class=case_history.models.PastHistoryForm)),
                ('history_of_suppression', djongo.models.fields.ArrayField(model_container=case_history.models.HistoryOfSuppression, model_form_class=case_history.models.HistoryOfSuppressionForm)),
                ('injuries', models.TextField(blank=True, null=True, verbose_name='Injuries')),
                ('accidents', models.TextField(blank=True, null=True, verbose_name='Accidents')),
                ('surgery', models.TextField(blank=True, null=True, verbose_name='Surgery')),
                ('history_of_children', djongo.models.fields.EmbeddedField(model_container=case_history.models.HistoryOfChildren, model_form_class=case_history.models.HistoryOfChildrenForm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Past History ',
                'verbose_name_plural': 'Case Past History',
                'db_table': 'ccrh_case_past_hist',
            },
        ),
        migrations.CreateModel(
            name='CaseObstetricHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('previous_pregnancies', djongo.models.fields.ArrayField(model_container=case_history.models.ObstetricHistory, model_form_class=case_history.models.ObstetricHistoryForm, null=True)),
                ('pregnancy', djongo.models.fields.ArrayField(model_container=case_history.models.Pregnancy, model_form_class=case_history.models.PregnancyForm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Obstetric History',
                'verbose_name_plural': 'Case Obstetric History',
                'db_table': 'ccrh_case_obstetric_history',
            },
        ),
        migrations.CreateModel(
            name='CaseMiasamaticAnalysis',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('predominant_miasm', djongo.models.fields.ArrayField(model_container=case_history.models.PredominantMiasm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Miasamatic Analysis',
                'verbose_name_plural': 'Case Miasamatic Analysis',
                'db_table': 'ccrh_case_miasamatic_analysis',
            },
        ),
        migrations.CreateModel(
            name='CaseMentalGeneral',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('mental_generals', djongo.models.fields.ArrayField(model_container=case_history.models.MentalGenerals, model_form_class=case_history.models.MentalGeneralsForm)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Mental General',
                'verbose_name_plural': 'Case Mental General',
                'db_table': 'ccrh_case_mental_general',
            },
        ),
        migrations.CreateModel(
            name='CaseHistoryPatientDetail',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('case_patient_name', models.CharField(max_length=100, verbose_name='Patient Name')),
                ('case_patient_father', models.CharField(blank=True, max_length=100, null=True, verbose_name="Patient's Father Name")),
                ('case_patient_mobile', models.BigIntegerField(blank=True, null=True, verbose_name='Patient Mobile Number ')),
                ('case_patient_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient Email')),
                ('case_patient_age', models.IntegerField(verbose_name='Patient Age')),
                ('case_patient_sex', models.CharField(help_text='Values will be stored as Male, Female, Others', max_length=100, verbose_name='Patient Sex')),
                ('case_patient_address', models.TextField(blank=True, null=True, verbose_name='Patient Address')),
                ('case_patient_occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient Occupation')),
                ('case_patient_marital_status', models.CharField(help_text='Values will be stored as Married, Unmarried, Divorced', max_length=100, verbose_name='Marital Status')),
                ('case_patient_education', models.CharField(blank=True, max_length=250, null=True, verbose_name='Education')),
                ('case_patient_pin_code', models.BigIntegerField(blank=True, null=True, verbose_name='Patient Pin Code ')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History ')),
                ('case_patient_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.City', verbose_name='City Name')),
                ('case_patient_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.State', verbose_name='State Name')),
            ],
            options={
                'verbose_name': 'Case History Patient Details',
                'verbose_name_plural': 'Case History Patient Details',
                'db_table': 'ccrh_case_history_patient_detail',
            },
        ),
        migrations.CreateModel(
            name='CaseGynaecologicalHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('menarche', djongo.models.fields.EmbeddedField(model_container=case_history.models.Menarche, model_form_class=case_history.models.MenarcheForm, null=True)),
                ('menstrual_cycle_particulars', djongo.models.fields.EmbeddedField(model_container=case_history.models.MenstrualCycleParticulars, model_form_class=case_history.models.MenstrualCycleParticularsForm, null=True)),
                ('abnormal_discharge', djongo.models.fields.EmbeddedField(model_container=case_history.models.AbnormalDischarge, model_form_class=case_history.models.AbnormalDischargeForm, null=True)),
                ('menopause', djongo.models.fields.EmbeddedField(model_container=case_history.models.Menopause, model_form_class=case_history.models.MenopauseForm, null=True)),
                ('ho_gynaecological_surgeries', djongo.models.fields.EmbeddedField(model_container=case_history.models.HoGynaecologicalSurgeries, model_form_class=case_history.models.HoGynaecologicalSurgeriesForm, null=True)),
                ('contraceptive_methods', djongo.models.fields.ArrayField(model_container=case_history.models.ContraceptiveMethods, model_form_class=case_history.models.ContraceptiveMethodsForm, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Gynaecological History',
                'verbose_name_plural': 'Case Gynaecological History',
                'db_table': 'ccrh_case_gynae_history',
            },
        ),
        migrations.CreateModel(
            name='CaseFamilyHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('family_history', djongo.models.fields.ArrayField(model_container=case_history.models.FamilyHistory, model_form_class=case_history.models.FamilyHistoryForm)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Family History',
                'verbose_name_plural': 'Case Family History',
                'db_table': 'ccrh_case_family_his',
            },
        ),
        migrations.CreateModel(
            name='CaseComplaints',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('symptoms', djongo.models.fields.ArrayField(model_container=case_history.models.Symptoms, model_form_class=case_history.models.SymptomsForm)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CaseComplaints', to='case_history.CaseHistory', verbose_name='Case History')),
            ],
            options={
                'verbose_name': 'Case Complaints',
                'verbose_name_plural': 'Case Complaints',
                'db_table': 'ccrh_case_complaints',
            },
        ),
        migrations.AddIndex(
            model_name='casehistorypatientdetail',
            index=models.Index(fields=['case_patient_name', 'case_patient_father', 'case_patient_sex', 'case_patient_city', 'case_patient_state'], name='ccrh_case_h_case_pa_2149c4_idx'),
        ),
    ]
